### ISSUE TITLE
Encourage semantic versioning driven by commit messages

### ISSUE THREAD

**Issue by kendrick** [compassion-gds/compassion-gds#122]
We'd love guidance on how to leverage semantic versioning to automate our release versioning and CHANGELOG creation wherever possible. One way we've seen this done is with thoughtful commit messages driven by a tool like [commitizen](https://commitizen-tools.github.io/commitizen/).

**Comment by kidroca** [comment]
Covered in #164 
Now part of the general contributing guidelines - [Commit Messages & Versioning](https://github.com/compassion-global-experience/compassion-design-system/blob/development/CONTRIBUTING.md#commit-messages--versioning)
