### ISSUE TITLE
Add modal component to vanilla and React components

### ISSUE THREAD

**Issue by kendrick** [compassion-gds/compassion-gds#127]
How might we share a11y- and behavior-related JavaScript across frameworks?

**Comment by kendrick** [comment]
We'll need to be careful to ensure our modal is accessible. Some patterns we could follow from [Deque Systems](https://dequeuniversity.com/library/aria/simple-dialog) and [a11y dev Scott O'Hara](https://scottaohara.github.io/accessible_modal_window/).

**Comment by kidroca** [comment]
So far we have the basic UI component for both vanilla and React
