### ISSUE TITLE
Replace hard-coded width values with tokens

### ISSUE THREAD

**Issue by kendrick** [compassion-gds/compassion-gds#135]
"Close the loop" we're creating in https://github.com/compassion-global-experience/cds-tokens/issues/20 by replacing the hard-coded values with token references. (Ref. https://github.com/compassion-global-experience/compassion-design-system/pull/133#discussion_r1069078276)

cc @KerimRahman, @kidroca, @sarsenault26 

---

### References to values not based on tokens:
The idea is to decide what should we do about these (case by case)
- create a token and update code
- do nothing, no need to create a token

1. https://github.com/compassion-global-experience/compassion-design-system/pull/142
    -  Checkbox/Radio - width/height: 22px https://github.com/compassion-global-experience/compassion-design-system/pull/142/files#diff-c3001b8974fb866682a51373f4cb2dfe8a5319b50a40af86026a3b4884d884b4R163-R164
    -  Radio:checked - border-width: 7px https://github.com/compassion-global-experience/compassion-design-system/pull/142/files#diff-c3001b8974fb866682a51373f4cb2dfe8a5319b50a40af86026a3b4884d884b4R178
    - Checkbox font size (icon): https://github.com/compassion-global-experience/compassion-design-system/pull/142/files#diff-c3001b8974fb866682a51373f4cb2dfe8a5319b50a40af86026a3b4884d884b4R208
    - Checkbox font (icon): https://github.com/compassion-global-experience/compassion-design-system/pull/142/files#diff-c3001b8974fb866682a51373f4cb2dfe8a5319b50a40af86026a3b4884d884b4R217

**Comment by kendrick** [comment]
Please list any concrete unit values anywhere in the project that should be tokenized as a comment in this issue.

**Comment by KerimRahman** [comment]
1. https://github.com/compassion-global-experience/compassion-design-system/pull/142

- [x] Checkbox/Radio - width/height: 22px
- [x] Radio:checked - border-width: 7px

**Comment by KerimRahman** [comment]
2. #145
Pin field width/height sizes:
- [x] Small - 32px
- [x] Medium (default) - 48px
- [x] Large - 52px

**Comment by KerimRahman** [comment]
3. Add design/styles/tokens for Backdrop/Overlay (used with Modal) component.
- Temporary solution: `{ position: 'fixed', inset: 0, background: 'black', opacity: 0.7 }`
