### ISSUE TITLE
Input: Editable Input behavior

### ISSUE THREAD

**Issue by kendrick** [compassion-gds/compassion-gds#43]
1. Looks like the input in read-only mode has a different width than in edit mode—this is leading to some horizontal shifting when toggling between the two modes
2. When the user enters edit mode, let's focus the input so they can immediately begin typing
3. In edit mode, let's toggle the edit icon to a button with a check mark, sitting next to a button with an 'x' or circle-slash icon. The latter should be disabled and both `visibility: hidden` and `aria-hidden="true"` should be set.

**Comment by jessicaskl** [comment]
Created a PR - linked to this issue. Let me know if there is anything I should fix. Thanks!
