### ISSUE TITLE
Responsive Image component

### ISSUE THREAD

**Issue by kendrick** [compassion-gds/compassion-gds#51]
## Behavior

1. Low-quality image placeholder with optional height and width attributes to prevent layout shift
2. If element is on-screen (or within xx pixels of screen), load the proper high-quality image (“proper” as defined by srcset)
3. Once image is loaded, use blur-up technique to transition between low-quality and high-quality
    - [On-point blur-up approach](https://benhoneywill.com/progressive-image-loading-with-react-hooks/)
4. If the client is in metered data/low bandwidth mode, show a placeholder over the LQIP and allow load-on-demand of the HQ image

## Options & Defaults

1. Width: fixed, constrained, full-width (see animation)
![Animated image widths](https://user-images.githubusercontent.com/189007/111345675-82334780-864b-11eb-8c7c-209ef27f43f4.gif)

2. Lazy-load: true by default
    - *[Create a Lazy-Loading Image Component with React Hooks](https://hangindev.com/blog/create-a-lazy-loading-image-component-with-react-hooks)*
3. Load-on-demand: Show the LQIP with a download indicator; don’t download the high-quality version without user action. False by default; true by default if client is in low-bandwidth mode
4. srcset params: array of CSS widths & corresponding image URLs
    - *[Responsive Images the Simple Way](https://cloudfour.com/thinks/responsive-images-the-simple-way/)*
    - [Responsive breakpoints generator](https://www.responsivebreakpoints.com/)

## Assumptions

* A service external to the GDS will provide dynamic resizing of images (based on a query param, filename, etc.) for LQIP and `srcset` purposes.

**Comment by cijhodges** [comment]
@kendrick 

I have everything minus the Load-on-demand functionality in origin/image and the preview image currently doesn't have an animation on it to un-blur: it just switches from the blurred view to the loaded image. 

I'll add some documentation to my code a little later today, as well as play around with the blur animation.
