### ISSUE TITLE
Timeline Component

### ISSUE THREAD

**Issue by kendrick** [compassion-gds/compassion-gds#54]
A Timeline component is design-complete in Figma but needs to be added to the React components. Gradient optional. 😉

![image](https://user-images.githubusercontent.com/189007/111349076-d2f86f80-864e-11eb-9544-8db83566087d.png)

**Comment by cijhodges** [comment]
https://user-images.githubusercontent.com/11335891/117848394-e0923600-b248-11eb-8df4-e085d23c246b.mov

@kendrick What do you think of this animation for the timeline?

**Comment by kendrick** [comment]
That’s lovely, @cijhodges! Definitely a keeper. I wonder about transitioning `border-radius` to turn the dashes into a solid line as the dot animates?

**Comment by cijhodges** [comment]
@kendrick That's a great idea. I have it currently just going straight to solid purple (that's not shown in the video.) But the extra animation to the dashes would be sweet. Also, sorry it took me so long to respond to this message. I didn't know I had a message waiting one me. 👎
