### ISSUE TITLE
Web component Icons

### ISSUE THREAD

**Issue by kidroca** [compassion-gds/compassion-gds#71]
We should probably not convert the React Icon components to web-components
The React components are generated from a script - we can do the same for web-components

Some points

#### Do we have to create icon components at all? 
The React components render a `svg` node, having a react component for this is convenient in React, but on pure web we can use an svg element directly or from an svg sprite

Should we create a web-component for each icon?
E.g. `gds-icon-add`, `gds-icon-circle`, `gds-icon-arrow-down` etc.. 

#### Importing the icons
It might not be a good idea to load and register all the icons when someone imports the `compassion/web-components` library (`customElements.define`), but only those the are actually used by the client
What will be the typical usage for `web-components`?
E.g. If the client loads everything they need from `web-components` at the top of the page - it might be tedious to list only the icons they're going to use and so they'll prefer to load all.

#### A `gds-icon` component with options
If we do a component maybe it should be a general icon web-component that accepts an `icon` or a `name` and renders the appropriate `svg` depending on the value
This would allow us to import icon svg source dynamically - the consumer of compassion/web-components won't have t load them all, or load separate icons manually. When a `gds-icon` is rendered we dynamically resolve it's content

#### Icons used in the React components that are converted to web-components
The icons used internally should be handled by the react to web-components converter and there shouldn't be any issues for them

**Comment by kendrick** [comment]
> The React components render a svg node, having a react component for this is convenient in React, but _on pure web we can use an svg element directly or from an svg sprite_

Agreed! In general I prefer SVG sprites in this case but given the (hopeful) breadth of usage of the DS we could end up with many special-use/single-use icons that aren’t used across many products. Because of this I’m inclined to focus on individual SVGs.

>E.g. If the client loads everything they need from web-components at the top of the page - it might be tedious to list only the icons they’re going to use and so they’ll prefer to load all.

Agreed; in non-framework contexts _I think_ it makes the most sense to recommend individual SVGs or to have a future tool in the DS that bundles SVGs into a custom per-site sprite sheet.

>If we do a component maybe it should be a general icon web-component that accepts an icon or a name and renders the appropriate svg depending on the value

💯. This is how I’ve handled icon components in the past—passing in an icon name as a prop/param—and it’s worked nicely.

**Comment by kidroca** [comment]
Alright so for the immediate future, it seems we should make a web component that accepts the `name` of the icon as string
Have all the SVGs bundled in `/assets/*.svg` and based on `name` dynamically load `/assets/{name}.svg` when it is used
