### ISSUE TITLE
[Web Components] Input/Edit does not render

### ISSUE THREAD

**Issue by kidroca** [compassion-gds/compassion-gds#76]
There's an error: 
> Uncaught ReferenceError: Fragment is not defined

Maybe we would have to use a wrapper element like `div` instead of a Fragment so that the React component can be converted correctly

**Comment by kidroca** [comment]
This is partially fixed but I found another issue happening 
![image](https://user-images.githubusercontent.com/12156624/126507873-73a766b1-0711-4fe5-8fd0-3c684cbd77da.png)

The way React-Web is build assets paths might be referenced incorrectly
![image](https://user-images.githubusercontent.com/12156624/126508429-31615dfe-258b-433d-a462-ded202905881.png)

The components bundled in `index.js` are referencing `check~UBWjaIYR.svg` as `src="check~UBWjaIYR.svg"` which does not resolve from the project folder of the `web-components` 
We should somehow tell the `src` that the image is in the same folder, or copy the `dist` content when we build the `web-components` project 
The problem might also be in the web components conversion ...

**Comment by kendrick** [comment]
The 3 SVGs in the screenshot should eventually be converted to `Icon` components, which I think will solve the issue. If we’re not ready to implement Icons here yet, copying the SVG to web-components and referencing it locally is fine for the short-term.
