### ISSUE TITLE
[Web|React] Thumbnail does not render

### ISSUE THREAD

**Issue by kidroca** [compassion-gds/compassion-gds#77]
The storybook page fails with (for both React and web-components)
> Cannot read property 'input' of undefined

https://xenodochial-pare-eb737a.netlify.app/?path=/story/global-design-system-thumbnail--preview

Thumbnail/Preview

**Comment by KerimRahman** [comment]
The comment from #76 about assets (https://github.com/compassion-gds/compassion-gds/issues/76#issuecomment-884249180) is valid here too, but the current issue is for another bug, so maybe we should create an assets related issue.
