### ISSUE TITLE
Deploy web components to Netlify

### ISSUE THREAD

**Issue by kendrick** [compassion-gds/compassion-gds#84]
@kidroca,

I’ve provisioned a Netlify site for the web components Storybook, but have noticed that a build is triggered for every commit to the monorepo—this means that a change in the React components will trigger a build in the web components, and vice versa.

Could we use a GitHub Action (or a pre-commit hook?) to build to a `react-web-storybook`/`web-components-storybook` branch and have Netlify watch those branches for changes?

**Comment by kidroca** [comment]
Yes, we can have a workflow/action setup that updates the said branches on merge/push to `main` (or maybe `development`?) 

But I thought it would also be possible to just monitor `main` (or `development`) and build for merges new commits there 
It should also be possible to monitor a branch and a folder (package). Though I don't know for Netlify and I don't have access

There's also a way to use `lerna` to only build whatever changed compared to a ref (e.g. previous merge to `main`) 

So the best thing IMO would be to 
1. run builds only for new commits in `main` (and/or `development`) 
2. optionally build only the package that changed 

If 2) is only possible by keeping separate `react-web-storybook`/`web-components-storybook` branches then we can do that as well 

BTW whenever `react-web` changes we should rebuild `web-components` as they are based on that package so it might be best to just build everything, just not for every commit but only for the commits in `main`

**Comment by kidroca** [comment]
No longer relevant
